In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline
Web_data_1 = pd.read_csv(r'C:\Users\User\Desktop\IronHack\Week_5\Day1\Project_2\vanguard-ab-test\data\raw\df_final_web_data_pt_1.txt')
Web_data_2 = pd.read_csv(r'C:\Users\User\Desktop\IronHack\Week_5\Day1\Project_2\vanguard-ab-test\data\raw\df_final_web_data_pt_2.txt')
Final_demo = pd.read_csv(r'C:\Users\User\Desktop\IronHack\Week_5\Day1\Project_2\vanguard-ab-test\data\raw\df_final_demo.txt')
Clients = pd.read_csv(r'C:\Users\User\Desktop\IronHack\Week_5\Day1\Project_2\vanguard-ab-test\data\raw\df_final_experiment_clients.txt')
display(Web_data_1)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
343136,2443347,465784886_73090545671,136329900_10529659391_316129,confirm,2017-03-31 15:15:46
343137,2443347,465784886_73090545671,136329900_10529659391_316129,step_3,2017-03-31 15:14:53
343138,2443347,465784886_73090545671,136329900_10529659391_316129,step_2,2017-03-31 15:12:08
343139,2443347,465784886_73090545671,136329900_10529659391_316129,step_1,2017-03-31 15:11:37
343140,2443347,465784886_73090545671,136329900_10529659391_316129,start,2017-03-31 15:10:47

## Dataset data 2

In [2]:
display(Web_data_2)

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58
...,...,...,...,...,...
412259,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
412260,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
412261,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
412262,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
412263,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

## Dataset Demo

In [3]:
display(Final_demo)

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

Concat datasets, data 1 and data 2

In [4]:
combined_df = pd.concat([Web_data_1, Web_data_2], ignore_index=True)
combined_df.drop_duplicates()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [5]:
display(combined_df)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

Merge combined dataset on client_id

In [6]:
merged = combined_df.merge(Clients, on='client_id', how='inner')

In [7]:
display(merged)

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
449826,9895983,473024645_56027518531,498981662_93503779869_272484,step_3,2017-06-15 19:52:09,NaN
449827,9895983,473024645_56027518531,498981662_93503779869_272484,step_2,2017-06-15 19:50:37,NaN
449828,9895983,473024645_56027518531,498981662_93503779869_272484,step_1,2017-06-15 19:50:05,NaN
449829,9895983,473024645_56027518531,498981662_93503779869_272484,start,2017-06-15 19:50:00,NaN
449830,9895983,473024645_56027518531,498981662_93503779869_272484,start,2017-06-15 19:44:05,NaN

Merge demo dataset with previous data

In [8]:
df = merged.merge(Final_demo, on='client_id', how='inner')
df.drop_duplicates()
display(df)

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449826,9895983,473024645_56027518531,498981662_93503779869_272484,step_3,2017-06-15 19:52:09,NaN,10.0,121.0,49.0,M,2.0,97748.22,2.0,2.0
449827,9895983,473024645_56027518531,498981662_93503779869_272484,step_2,2017-06-15 19:50:37,NaN,10.0,121.0,49.0,M,2.0,97748.22,2.0,2.0
449828,9895983,473024645_56027518531,498981662_93503779869_272484,step_1,2017-06-15 19:50:05,NaN,10.0,121.0,49.0,M,2.0,97748.22,2.0,2.0
449829,9895983,473024645_56027518531,498981662_93503779869_272484,start,2017-06-15 19:50:00,NaN,10.0,121.0,49.0,M,2.0,97748.22,2.0,2.0
449830,9895983,473024645_56027518531,498981662_93503779869_272484,start,2017-06-15 19:44:05,NaN,10.0,121.0,49.0,M,2.0,97748.22,2.0,2.0

In [9]:
df.to_csv("data.csv", index=False)

Unique values for client

In [10]:
df['client_id'].nunique()

70609

Average age of clients

In [11]:
avg_age = df.groupby('client_id')['clnt_age'].first().mean()
avg_age

np.float64(46.442240133722414)

In [12]:
df['Variation'].value_counts()

Variation
Test       177847
Control    143462
Name: count, dtype: int64

Count of gender of clients

In [13]:
count_gender = df.groupby('client_id')['gendr'].first()
count_gender.value_counts()

gendr
U    24122
M    23724
F    22746
X        3
Name: count, dtype: int64

In [14]:
avg_tenure = df.groupby('client_id')['clnt_tenure_yr'].first().mean()
avg_tenure

np.float64(12.052949925632127)

In [15]:
count_tenure = df.groupby('client_id')['clnt_tenure_yr'].first()
count_tenure.value_counts()

clnt_tenure_yr
6.0     7092
5.0     6955
7.0     4955
4.0     4687
15.0    4564
8.0     4045
14.0    3646
12.0    3631
13.0    3607
9.0     3357
11.0    2920
10.0    2775
16.0    2714
21.0    2257
20.0    1580
22.0    1492
17.0    1373
23.0    1279
18.0    1206
19.0    1153
24.0     846
26.0     660
27.0     632
28.0     507
25.0     484
3.0      449
29.0     309
30.0     303
33.0     206
32.0     191
34.0     175
31.0     166
35.0     102
2.0       81
36.0      36
37.0      35
38.0      33
48.0      16
39.0       9
55.0       9
40.0       9
50.0       8
43.0       6
47.0       6
42.0       6
51.0       5
46.0       5
49.0       4
44.0       3
52.0       2
45.0       1
62.0       1
41.0       1
54.0       1
Name: count, dtype: int64

In [16]:
df_test = df[df['Variation']== 'Test']
df_test

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417646,1574008,117364417_77840596075,528720790_71583064618_169151,confirm,2017-05-06 23:51:05,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
417647,1574008,117364417_77840596075,528720790_71583064618_169151,step_3,2017-05-06 23:50:40,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
417648,1574008,117364417_77840596075,528720790_71583064618_169151,step_2,2017-05-06 23:43:47,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
417649,1574008,117364417_77840596075,528720790_71583064618_169151,step_1,2017-05-06 23:43:34,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0
417650,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test,10.0,121.0,55.0,U,2.0,153238.83,3.0,6.0

In [17]:
df_test["client_id"].nunique()

26968

In [18]:
df_test = df_test.sort_values(by=['client_id','visit_id','process_step','date_time'])
df_test

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,3.0,46.0,29.5,U,2.0,25454.66,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372490,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,10.0,124.0,31.0,F,3.0,107059.74,6.0,9.0
105350,9999729,604429154_69247391147,99583652_41711450505_426179,start,2017-04-05 13:40:49,Test,10.0,124.0,31.0,F,3.0,107059.74,6.0,9.0
105349,9999729,604429154_69247391147,99583652_41711450505_426179,step_1,2017-04-05 13:41:04,Test,10.0,124.0,31.0,F,3.0,107059.74,6.0,9.0
341321,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,23.0,281.0,49.0,F,2.0,431887.61,1.0,4.0
341320,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,23.0,281.0,49.0,F,2.0,431887.61,1.0,4.0

## Group Control

In [19]:
df_control = df[df['Variation']== 'Control']
df_control

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
13,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:03,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
14,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:01,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
15,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:28:52,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
16,4033851,762728880_76361333336,949661017_22392791362_127391,step_3,2017-04-05 12:26:08,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
17,4033851,762728880_76361333336,949661017_22392791362_127391,step_2,2017-04-05 12:24:43,Control,12.0,149.0,63.5,M,2.0,142642.26,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417643,433098,5505424_50616523266,773565250_67577573147_389841,start,2017-05-13 15:30:47,Control,6.0,73.0,25.0,U,2.0,34419.62,2.0,5.0
417651,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
417652,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
417653,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0
417654,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control,21.0,252.0,34.0,M,3.0,141808.05,6.0,9.0

All visits with ended , confirmed

In [20]:
steps = ['start','step_1','step_2','step_3','confirm']

In [21]:
def error_by_step(df):
    
    all_visits = df['visit_id'].nunique()

    for i in range(len(steps) -1): ## -1 , not for confirmed steps
        step_current = steps[i]
        step_next = steps[i+1]

        visit_step_current = set(df[df['process_step'] == step_current]['visit_id'])
        visit_step_next = set(df[df['process_step'] == step_next]['visit_id'])

        error = visit_step_current - visit_step_next

        percentage_error = (len(error) / all_visits)*100

        print(f'Error on {step_current} to {step_next} is: {percentage_error:.2f}%')

In [22]:
visit_confirmed = df_control[df_control['process_step'] == 'confirm']['visit_id'].unique()
visit_confirmed

array(['949661017_22392791362_127391', '754106292_61370647593_160929',
       '284161492_75966778593_698992', ...,
       '423005536_66563748376_701196', '685634090_42070675506_389171',
       '773565250_67577573147_389841'], shape=(16046,), dtype=object)

All visits withou confirm

In [23]:
all_visits = df_control['visit_id'].unique()
visits_without_confirm = set(all_visits) - set(visit_confirmed)

In [24]:
all_visits

array(['949661017_22392791362_127391', '116640698_27328181095_188045',
       '754106292_61370647593_160929', ...,
       '685634090_42070675506_389171', '773565250_67577573147_389841',
       '562606085_36368381773_92090'], shape=(32189,), dtype=object)

Clients with errors

In [25]:
clients_with_error = df_control[df_control['visit_id'].isin(visits_without_confirm)]['client_id'].unique()

Unique clients in control

In [26]:
total_clients = df_control['client_id'].nunique()
total_clients

23532

In [27]:
qty_client_error = len(clients_with_error)
qty_client_error

12054

In [28]:
percentage_error = (qty_client_error/total_clients) * 100
percentage_error

51.223865374808774

Error by steps:

In [29]:
print(error_by_step(df_control))

Error on start to step_1 is: 23.70%
Error on step_1 to step_2 is: 10.94%
Error on step_2 to step_3 is: 6.42%
Error on step_3 to confirm is: 9.46%
None

In [30]:
types = ['test','control']

In [31]:
type_group = df_test['Variation'].unique()[0]

In [32]:
visit_confirmed_test = visit_confirmed.shape[0]

In [33]:
visit_confirmed
visit_confirmed_test

16046

In [34]:
all_test_visits = all_visits.shape[0]

In [35]:
test_visits_without_confirm = len(visits_without_confirm)

In [36]:
test_clients_with_error = clients_with_error.shape[0]

## Test Group

In [37]:
visit_confirmed_test = df_test[df_test['process_step'] == 'confirm']['visit_id'].unique()
visit_confirmed_test

array(['637149525_38041617439_716659', '40369564_40101682850_311847',
       '583743392_96265099036_939815', ...,
       '149965839_24823291142_245569', '288904166_90826265353_276104',
       '870243567_56915814033_814203'], shape=(21731,), dtype=object)

In [38]:
all_visits_test = df_test['visit_id'].unique()
visits_without_confirm_test = set(all_visits_test) - set(visit_confirmed_test)

In [39]:
clients_with_error_test = df_test[df_test['visit_id'].isin(visits_without_confirm_test)]['client_id'].unique()
clients_with_error_test

array([    934,    1346,    1516, ..., 9999626, 9999729, 9999832],
      shape=(11905,))

In [40]:
total_clients_test = df_test['client_id'].nunique()
total_clients_test

26968

In [41]:
qty_client_error_test = len(clients_with_error_test)
qty_client_error_test

11905

In [42]:
percentage_error_test = (qty_client_error_test/total_clients_test) * 100
percentage_error_test

44.144912488875704

In [43]:
print(error_by_step(df_test))

Error on start to step_1 is: 13.82%
Error on step_1 to step_2 is: 10.61%
Error on step_2 to step_3 is: 6.95%
Error on step_3 to confirm is: 10.36%
None

percentage_error_test = percentage per unique client, with at least 1 visit thta didnd t ended ,
error_by_step = percentage per visit that didnt pass for the next step

## Test group
percentage_error = 44.144912488875704
Error on start to step_1 is: 13.82%
Error on step_1 to step_2 is: 10.61%
Error on step_2 to step_3 is: 6.95%
Error on step_3 to confirm is: 10.36%


Control group
percentage_error = 51.223865374808774
Error on start to step_1 is: 23.70%
Error on step_1 to step_2 is: 10.94%
Error on step_2 to step_3 is: 6.42%
Error on step_3 to confirm is: 9.46%


Its posible to analize that, the clients from the group Control have commited more erros then clients from Test groups, at any visit. 
Also, we can see that the errors by steps are almost the same between both groups. The difference is at the start to step 1 , where clients from the group Control leave almost 10% more at this step.

In [44]:
# A/B test:
# Determine if the completion rate ( confirm step) is higher in Test Group than in the Control Group.

In [45]:
#Hypothesis

#H0: mu_confirm_test  <= mu_confirm_control
#H1: mu_confirm_test > mu_confirm_control

#significance level = 0.05

Total number of unique visits:

In [46]:
visits_control = df_control['visit_id'].nunique()
visits_control

32189

In [47]:
visits_test = df_test['visit_id'].nunique()

Visits that ended on confirm:

In [48]:
confirm_test = df_test[df_test['process_step'] == 'confirm']['visit_id'].nunique()
confirm_test

21731

In [49]:
confirm_control = df_control[df_control['process_step'] == 'confirm']['visit_id'].nunique()
confirm_control

16046

'Confirm' rate

In [50]:
r_test = confirm_test / visits_test
r_test

0.5851734166307626

In [51]:
r_control = confirm_control /visits_control
r_control

0.4984932740998478

In [52]:
import scipy.stats as st

In [53]:
from statsmodels.stats.proportion import proportions_ztest

In [54]:
succes = [confirm_test,confirm_control]
succes

[21731, 16046]

In [55]:
sample = [visits_test,visits_control]
sample

[37136, 32189]

In [56]:
stat, p_value = proportions_ztest(succes,sample, alternative='larger')
stat, p_value

(np.float64(22.85684118615931), np.float64(6.247505366322125e-116))

In [57]:
p_value1 = 6.247505366322125e-116

In [58]:
alpha = 0.05
if p_value < alpha:
    print('Reject null hypothesis.')
else:
    print('Do not reject null hypothesis.')

Reject null hypothesis.

In [59]:
total_clients_control = df_control['client_id'].nunique()
total_clients_control

23532

In [60]:
total_clients_test = df_test['client_id'].nunique()
total_clients_test

26968

In [67]:
total_visit_test = df_test['visit_id'].nunique()
total_visit_test

37136

In [69]:
total_visit_control = df_control['visit_id'].nunique()
total_visit_control

32189

In [101]:
visit_step_current = set(df_test[df_test['process_step'] == 'start']['visit_id'])
visit_step_next = set(df_test[df_test['process_step'] == 'step_1']['visit_id'])

error = visit_step_current - visit_step_next

error_start_to_step_1_test = (len(error) / total_visit_test)*100
error_start_to_step_1_test

13.824859974149073

In [102]:
visit_step_current = set(df_control[df_control['process_step'] == 'start']['visit_id'])
visit_step_next = set(df_control[df_control['process_step'] == 'step_1']['visit_id'])

error = visit_step_current - visit_step_next

error_start_to_step_1_control = (len(error) / total_visit_control)*100
error_start_to_step_1_control

23.70064307682749

In [103]:
visit_step_current = set(df_test[df_test['process_step'] == 'step_1']['visit_id'])
visit_step_next = set(df_test[df_test['process_step'] == 'step_2']['visit_id'])

error = visit_step_current - visit_step_next

error_step_1_to_step_2_test = (len(error) / total_visit_test)*100
error_step_1_to_step_2_test

10.61234381732012

In [104]:
visit_step_current = set(df_control[df_control['process_step'] == 'step_1']['visit_id'])
visit_step_next = set(df_control[df_control['process_step'] == 'step_2']['visit_id'])

error = visit_step_current - visit_step_next

error_step_1_to_step_2_control = (len(error) / total_visit_control)*100
error_step_1_to_step_2_control

10.944732672652147

In [132]:
visit_step_current = set(df_test[df_test['process_step'] == 'step_2']['visit_id'])
visit_step_next = set(df_test[df_test['process_step'] == 'step_3']['visit_id'])

error = visit_step_current - visit_step_next

error_step_2_to_step_3_test = (len(error) / total_visit_test)*100
error_step_2_to_step_3_test

6.952822059457131

In [133]:
visit_step_current = set(df_test[df_test['process_step'] == 'step_3']['visit_id'])
visit_step_next = set(df_test[df_test['process_step'] == 'confirm']['visit_id'])

error = visit_step_current - visit_step_next

error_step_3_to_confirm_test = (len(error) / total_visit_test)*100
error_step_3_to_confirm_test

10.364605773373546

In [168]:
error_client_01 = df_test[df_test['client_id'] == 1545935].sort_values(by=['date_time'], ascending=False)
error_client_01

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
341028,1545935,173739692821351976381129,10056419_61656665964_803695,confirm,2017-06-20 23:21:23,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0
341029,1545935,173739692821351976381129,10056419_61656665964_803695,step_3,2017-06-20 23:20:34,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0
341030,1545935,173739692821351976381129,10056419_61656665964_803695,step_2,2017-06-20 23:17:58,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0
341031,1545935,173739692821351976381129,10056419_61656665964_803695,step_1,2017-06-20 23:17:45,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0
341032,1545935,173739692821351976381129,10056419_61656665964_803695,start,2017-06-20 23:17:42,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0
341033,1545935,173739692821351976381129,10056419_61656665964_803695,step_1,2017-06-20 23:13:57,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0
341034,1545935,173739692821351976381129,10056419_61656665964_803695,start,2017-06-20 23:13:46,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0

In [181]:
step_order = {'start':4, 'step_1':3, 'step_2':2, 'step_3':1, 'confirm':0}

In [182]:
error_client_01['step_error'] = error_client_01['process_step'].map(step_order)

In [183]:
error_client_01 = error_client_01.reset_index(drop=True)
error_client_01.head(20)

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,step_error
0,1545935,173739692821351976381129,10056419_61656665964_803695,confirm,2017-06-20 23:21:23,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0,0
1,1545935,173739692821351976381129,10056419_61656665964_803695,step_3,2017-06-20 23:20:34,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0,1
2,1545935,173739692821351976381129,10056419_61656665964_803695,step_2,2017-06-20 23:17:58,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0,2
3,1545935,173739692821351976381129,10056419_61656665964_803695,step_1,2017-06-20 23:17:45,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0,3
4,1545935,173739692821351976381129,10056419_61656665964_803695,start,2017-06-20 23:17:42,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0,4
5,1545935,173739692821351976381129,10056419_61656665964_803695,step_1,2017-06-20 23:13:57,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0,3
6,1545935,173739692821351976381129,10056419_61656665964_803695,start,2017-06-20 23:13:46,Test,4.0,59.0,24.0,F,3.0,52280.32,5.0,8.0,4

In [198]:
errors = 0


for i in range(1,len(error_client_01)):
    if error_client_01.loc[i,'step_error']< error_client_01.loc[i-1,'step_error']:
        errors += 1

print(f'Total of errors is: {errors} errors.')

Total of errors is: 1 errors.

In [201]:
def count_step_errors(step_list):
    errors = 0
    for i in range(1,len(error_client_01)):
        if error_client_01.loc[i,'step_error']< error_client_01.loc[i-1,'step_error']:
            errors += 1
    return errors

In [203]:
errors_by_visit = (error_client_01.groupby('visit_id')['step_error'].apply(list).apply(count_step_errors))
print(errors_by_visit)

visit_id
10056419_61656665964_803695    1
Name: step_error, dtype: int64

In [206]:
new_test = df_test.sort_values(by=['date_time'], ascending=False)

In [207]:
new_test['step_error'] = new_test['process_step'].map(step_order)

In [209]:
all_errors_test = (new_test.groupby('visit_id')['step_error'].apply(list).apply(count_step_errors))
all_errors_test

visit_id
100012776_37918976071_457913    1
100019538_17884295066_43909     1
100022086_87870757897_149620    1
100173292_91322748906_143563    1
100217156_67053490690_383412    1
                               ..
999960019_60838685252_926860    1
999971096_28827267783_236076    1
999976049_95772503197_182554    1
999984454_18731538378_781808    1
999988789_76411676596_272843    1
Name: step_error, Length: 37136, dtype: int64

In [107]:
total_clients_test

26968

In [108]:
len(error)

3849

In [109]:
data = {
'Group': ['Test','Control'],
'clients_with_error':[percentage_error_test,percentage_error],
'error_start_to_step_1':[error_start_to_step_1_test,error_start_to_step_1_control],
'error_step_1_to_step_2':[error_step_1_to_step_2_test,error_step_1_to_step_2_control],
'error_step_2_to_step_3':[error_step_2_to_step_3_test,6.42],
'error_step_3_to_confirm':[error_step_3_to_confirm_test,9.46],
'total_clients' : [total_clients_test,total_clients_control],
'clients_with_error' : [qty_client_error_test,qty_client_error],
'p_value':[p_value1,'-']

}

In [115]:
data_tc = pd.DataFrame(data)
data_tc

,Group,clients_with_error,error_start_to_step_1,error_step_1_to_step_2,error_step_2_to_step_3,error_step_3_to_confirm,total_clients,p_value
0,Test,11905,13.824860,10.612344,6.952822,10.364606,26968,0.0
1,Control,12054,23.700643,10.944733,6.420000,9.460000,23532,-

In [116]:
data_tc.dtypes

Group                       object
clients_with_error           int64
error_start_to_step_1      float64
error_step_1_to_step_2     float64
error_step_2_to_step_3     float64
error_step_3_to_confirm    float64
total_clients                int64
p_value                     object
dtype: object

In [117]:
data_tc.to_csv("datatc.csv", index=False)

In [120]:
df_test['process_step'].value_counts()

process_step
start      56474
step_1     38768
step_2     30989
step_3     25894
confirm    25722
Name: count, dtype: int64

In [121]:
df_control['process_step'].value_counts()

process_step
start      47608
step_1     29668
step_2     25886
step_3     22795
confirm    17505
Name: count, dtype: int64

In [186]:
df['gendr'].value_counts()

gendr
M    151877
U    151608
F    146217
X        14
Name: count, dtype: int64